#!/bin/bash

[ -z $TMUX ] && echo "start tmux" && exit

sort -u bash_history > bash_history_ && mv bash_history_ bash_history

ansible-playbook --check playbook.yml || exit
ansible-playbook --syntax-check playbook.yml || exit
ansible-lint playbook.yml

rm *.retry
> log

vagrant destroy -f
for vm in $(sudo virsh list --all --name); do
	sudo virsh destroy $vm;
	sudo virsh undefine $vm;
done

for vol in $(sudo virsh vol-list default | awk '! /centos/ && /img/{ print  $1 }'); do
	sudo virsh vol-delete --pool default $vol;
done

rm -rf .vagrant

vagrant up $* && \
	tmux new-window -n admin 'vagrant ssh master' && \
	tmux new-window -n token 'vagrant ssh master -c "echo && sudo cat /root/token && echo "' \; setw remain-on-exit && \
	tmux new-window -n all-nodes 'vagrant ssh master' \; split-window 'vagrant ssh node1' \; split-window 'vagrant ssh node2' \; split-window 'vagrant ssh node3' \; setw synchronize-panes \; nextl \; nextl \; nextl \; nextl \; nextl && \
	tmux new-window -n master-and-portfw 'vagrant ssh master -c "sudo watch kubectl --kubeconfig=/etc/kubernetes/admin.conf get pods --all-namespaces -o wide" -- -L 8001:localhost:8001'
